name = "eren"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTYzOWQxNjQtODI0MS00MzI2LWIxNWItOTAzMmJmNDA5OGE3IiwidGVuYW50X2lkIjoiZDZmMGMxNTMzZTg2MGM3ZDFjY2EyMDdhMTJjNzBjNThiNTUyYWMxODU1NjRjODg0ZTAwZTFjOTg3NzRiMDdiYyIsImludGVybmFsX3NlY3JldCI6ImQ1YWE5MjZkLTE5ZWYtNGI1MS05ZTU1LTE0YjU4OGRmZjE3YSJ9.bldNTTHAnSkZD0aVzMDaPorwgxnWIwrAscmzWcUthnY"

JWT_SECRET = "meet1234"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
